#!/bin/sh /etc/rc.common
# procd init script for u60-datad. Install to /etc/init.d/u60-datad, then:
#   /etc/init.d/u60-datad enable && /etc/init.d/u60-datad start
# SPDX-License-Identifier: MIT

START=96
USE_PROCD=1
DIR=/data/u60pro
PROG=$DIR/u60-datad

start_service() {
    [ -x "$PROG" ] || return 1
    procd_open_instance
    procd_set_param command "$PROG" -i 1000
    procd_set_param respawn
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}
