#!/bin/sh /etc/rc.common
# procd init script for zwrt-datad. Install to /etc/init.d/zwrt-datad, then:
#   /etc/init.d/zwrt-datad enable && /etc/init.d/zwrt-datad start
# SPDX-License-Identifier: MIT

START=96
USE_PROCD=1
DIR=/data/zwrt-datad
PROG=$DIR/zwrt-datad
LAN_PORT=9461
TOKEN_FILE=$DIR/auth.token

start_service() {
    [ -x "$PROG" ] || return 1
    procd_open_instance
    procd_set_param command "$PROG" -i 1000
    procd_append_param command --lan-bind 0.0.0.0 --lan-port "$LAN_PORT" \
        --auth-token-file "$TOKEN_FILE"
    procd_set_param respawn
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}
